### ISSUE TITLE
ETA for release/beta?

### ISSUE THREAD

**Issue by yashwanthm** [fusioncharts/react-native-fusioncharts#1]
Just stumbled onto this. Struck with a requirement for a charting library that works across React Native and React JS. You already have a react library for Fusion Charts. Would this(RN Fusion charts) still use the same data scheme as the React JS version ?
Also, what is the ETA expected?

**Comment by rousan** [comment]
Hello @yashwanthm,
We published our first release [1.0.0](https://github.com/fusioncharts/react-native-fusioncharts/releases/tag/1.0.0),  Check it out and let us know if you face any problems.
