### ISSUE TITLE
I want to show msline chart without categories, is it possible. Its not woking ?

### ISSUE THREAD

**Issue by AmeyKhoje** [fusioncharts/react-native-fusioncharts#125]
`const chartConfig = {
        type: 'msline',
        width: Dimensions.get('window').width, // Width of the chart
        height: 400,
        dataFormat: 'json',
        dataSource: {
            chart: {
                caption: 'Historical Temperature Data',
                subCaption: '',
                xAxisName: null,
                yAxisName: "Temperature in deg.C",
                numberSuffix: '',
                theme: 'fusion',
                showXAxisValues: true,
                rotateXAxisName: 1,
                // showYAxisLine: true,
                plottooltext: '$label, $value deg.C',
                tooltipBgColor: 'rgba(203, 0, 0, 0,1)',
                tooltipBorderColor: ColorPalette.Grey,
                showTooltipShadow: true,
                tooltipColor: ColorPalette.White,
                tooltipbgalpha: '70',
                tooltipBorderRadius: '5',
                tooltipBorderThickness: '0',
                tooltipPadding: '8',
                showValues: true,
                maxBarHeight: 20,
                showXAxisLine: true
            },
            categories: [
                {
                    category: []
                }
            ],
            dataSet: chartData
        }`

Here my chartconfig. Please help me how to render chart without categories. ?

**Comment by AyanBhadury** [comment]
@AmeyKhoje :

As per your given requirement, the categories cannot be removed from a msline line chart as the x-axis labels are dependent upon the categories. If you don't want categories, we would suggest using a single series line chart, where you can set labels in the data object. Kindly note that multi-series data plotting will not be possible using a single series line chart.

**Comment by AmeyKhoje** [comment]
Thank you
