### ISSUE TITLE
Different legend icons for msline and mscolumn2d with the same configuration

### ISSUE THREAD

**Issue by osvald0** [fusioncharts/react-native-fusioncharts#126]
`msline` and `mscolumn2d` charts legend icons looks different with similar configuration.

`msline` configuration:

```
{
    theme: 'fusion',
    numberPrefix: '$',
    bgColor: styles.charBackgroundColor,
    canvasbgColor: styles.charBackgroundColor,
    toolTipBgColor: styles.charBackgroundColor,
    toolTipColor: styles.text,
    divLineColor: styles.divLine,
    baseFontColor: styles.text,
    outCnvBaseFontSize: 10,
    chartLeftMargin: 0,
    chartTopMargin: 10,
    chartRightMargin: 10,
    // legend configuration.
    legendIconSides: 1,
    legendIconScale: 0.6,
    legendItemFontSize: 10,
    legendItemFontColor: styles.text,
    legendIconBgAlpha: 0,
  }
```

`mscolumn2d`  configuration: 

```
{
    theme: 'fusion',
    numberPrefix: '$',
    bgColor: styles.charBackgroundColor,
    canvasbgColor: styles.charBackgroundColor,
    toolTipBgColor: styles.charBackgroundColor,
    toolTipColor: styles.text,
    divLineColor: styles.divLine,
    baseFontColor: styles.text,
    outCnvBaseFontSize: 10,
    chartLeftMargin: 0,
    chartTopMargin: 10,
    chartRightMargin: 0,
    // legend configuration.
    legendIconSides: 1,
    legendIconScale: 0.6,
    legendItemFontSize: 10,
    legendItemFontColor: styles.text,
  }
```

![msline](https://user-images.githubusercontent.com/20977158/124150269-cb2ad280-da67-11eb-91f9-1c38e6e31b6c.png)

![mscolumn2d](https://user-images.githubusercontent.com/20977158/124150301-d251e080-da67-11eb-9700-4727ac194f26.png)

**Comment by AyanBhadury** [comment]
@osvald0 As per your given query would suggest you follow the below-given steps.

Set the legendIconBgAlpha to 100.

Set the "anchorBgColor" in your dataset with your required color hex codes. 

In msline, the legends are based on the anchors in the data plot and as per your given sample code, the anchors appear to be blank hence, the labels were blank as well. 

Please find the link to a working sample: http://jsfiddle.net/rs7fu0La/1/

**Comment by osvald0** [comment]
It works fine. Thanks!
