### ISSUE TITLE
I can't set transparent background

### ISSUE THREAD

**Issue by osvald0** [fusioncharts/react-native-fusioncharts#128]
I'm trying to set a transparent background with canvasBgAlpha and bgAlpha but this just change the background color to white.
What is the configuration to set a transparent background?

react: 17.0.1
react-native: 0.64.2
react-native-fusioncharts: 5.1.0

**Comment by AyanBhadury** [comment]
@osvald0 Please set containerBackgroundOpacity prop as 0

` <ReactNativeFusionCharts
            chartConfig={this.state.chartConfig}
            containerBackgroundOpacity= "0"
          />`
