### ISSUE TITLE
how to install on Expo.io

### ISSUE THREAD

**Issue by isthaison** [fusioncharts/react-native-fusioncharts#2]

**Comment by rousan** [comment]
Hi @isthaison 

Follow the steps below to setup [react-native-fusioncharts](https://github.com/fusioncharts/react-native-fusioncharts) library in your `Expo React Native` app:

* Install `react-native-fusioncharts` module from `npm`:

```bash
npm install --save react-native-fusioncharts
```

* Create `assets` folder in your project root if it doesn't exist.
* Copy `FusionCharts` library in this `assets` folder (requires only when the licensed version of `FusionCharts` is used).
* Create a file named `fusioncharts-tpl.html` in this `assets` folder with the required `FusionCharts` module files. Find the sample HTML file [here](https://github.com/fusioncharts/react-native-fusioncharts/blob/master/templates/fuioncharts-tpl-ios.html).
* Add a `build:assets` script in Application's `package.json` file as follows:

`package.json file:`

```javascript
  ......

  "scripts": {
    ......

    "build:assets": "fc-build-assets --fc-template ./assets/fusioncharts-tpl.html --fc-library ./assets/fusioncharts"
  },

  ......
```

The `--fc-library ./assets/fusioncharts` option is only required when you copied `FusionCharts` library in your assets folder.
* Import `react-native-fusioncharts` library as follows:

The `App.js` file:
```javascript
import React, { Component } from 'react';
import { AppRegistry, StyleSheet, Text, View, Platform } from 'react-native';
import FusionCharts from 'react-native-fusioncharts';

export default class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      type: 'column2d',
      width: '100%',
      height: '100%',
      dataFormat: 'json',
      dataSource: {
            "chart": {
                "caption": "Harry's SuperMart",
                "subCaption": "Top 5 stores in last month by revenue",
                "numberprefix": "$",
                "theme": "fint"
            },
            "data": [
                {
                    "label": "Bakersfield Central",
                    "value": "880000"
                },
                {
                    "label": "Garden Groove harbour",
                    "value": "730000"
                }, 
                {
                    "label": "Los Angeles Topanga",
                    "value": "590000"
                },
                {
                    "label": "Compton-Rancho Dom",
                    "value": "520000"
                },
                {
                    "label": "Daly City Serramonte",
                    "value": "330000"
                }
            ]
        }
    };

    this.libraryPath = require('./assets/fusioncharts.html');
  } 

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.heading}>
          FusionCharts Integration with React Native
        </Text>
        <View style={styles.chartContainer}>
          <FusionCharts
            type={this.state.type}
            width={this.state.width}
            height={this.state.height}
            dataFormat={this.state.dataFormat}
            dataSource={this.state.dataSource}
            libraryPath={this.libraryPath} // set the libraryPath property
          />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10
  },
  heading: {
    fontSize: 20,
    textAlign: 'center',
    marginBottom: 10
  },
  chartContainer: {
    height: 200
  }
});
```

* Run the following command before running the app:

```bash
npm run build:assets
```

*  Run the app:

```bash
exp start
```

Let us know if you face any problems.
Thanks.

**Comment by isthaison** [comment]
Hi @rousan!
thanks you, i got it

**Comment by isthaison** [comment]
![image](https://user-images.githubusercontent.com/22739578/35366659-21e855bc-01ad-11e8-8758-5c0751da13e0.png)
![image](https://user-images.githubusercontent.com/22739578/35366703-4ab7c8ce-01ad-11e8-8fd0-8c0f817818b8.png)

i have done the step! help~~~

**Comment by rousan** [comment]
Hello @isthaison,

The problem is raised because of the steps mentioned above are not followed correctly.
Please create a file named `fusioncharts-tpl.html` in your `assets` folder with following contents:
```html
<!DOCTYPE html>
<html>

<head>
  <!-- Include the required FusionCharts modules -->
  <script type='text/javascript' src="fusioncharts/fusioncharts.js"></script>
  <script type='text/javascript' src="fusioncharts/fusioncharts.charts.js"></script>
  <script type='text/javascript' src="fusioncharts/fusioncharts.powercharts.js"></script>
  <script type='text/javascript' src="fusioncharts/fusioncharts.maps.js"></script>
  <script type='text/javascript' src="fusioncharts/maps/fusioncharts.usa.js"></script>
  <script type='text/javascript' src="fusioncharts/maps/fusioncharts.world.js"></script>
  <script type='text/javascript' src="fusioncharts/themes/fusioncharts.theme.fint.js"></script>
  <script type='text/javascript' src="fusioncharts/themes/fusioncharts.theme.ocean.js"></script>
</head>

<body></body>

</html>
```
Then write the `build:assets` script in Application's `package.json` with following contents:
```javascript
......

  "scripts": {
    ......

    "build:assets": "fc-build-assets --fc-template ./assets/fusioncharts-tpl.html --fc-library ./assets/fusioncharts"
  },

  ......
```
Then run `npm run build:assets` command before executing the application.

Let us know if you face any problems.
Thanks.

**Comment by rousan** [comment]
@isthaison, You are welcome.

**Comment by isthaison** [comment]
best regards

**Comment by ajaspartnfd** [comment]
Hello,

I followed the steps and I get the html of the generated /assets/fusioncharts.html
Why is that? What did I miss?

![image](https://user-images.githubusercontent.com/32884304/90355207-af6a3980-e019-11ea-9128-73b963686bf1.png)

Thank you very much for your help and support.

**Comment by azha1983** [comment]
> Hello,
> 
> I followed the steps and I get the html of the generated /assets/fusioncharts.html
> Why is that? What did I miss?
> 
> ![image](https://user-images.githubusercontent.com/32884304/90355207-af6a3980-e019-11ea-9128-73b963686bf1.png)
> 
> Thank you very much for your help and support.

same with me...when i ask fusiona support , he reply it is not problem with fusion..it is a problem with expo and give me this link... https://github.com/react-native-webview/react-native-webview/issues/428

i ve been try 2 day to make fusion chart running on android but still no result. but it is work perfectly on ios. unfortunately my company already bought the license, if not i just use other chart
