### ISSUE TITLE
scroll chart

### ISSUE THREAD

**Issue by isthaison** [fusioncharts/react-native-fusioncharts#3]
With big data, do not know support scrollview ?
example
 https://www.fusioncharts.com/dev/chart-guide/scroll-charts/creating-scroll-charts.html

**Comment by rousan** [comment]
Hi @isthaison,

`Scroll Chart` allows you to plot large quantities of data and also `react-native-fusioncharts` supports scroll chart with large data.

**Comment by isthaison** [comment]
i have test with big data but not working , It see responsive!

**Comment by rousan** [comment]
Hi @isthaison,
can you provide sample source code that can produce the same at our end?

**Comment by isthaison** [comment]
https://snack.expo.io/@isthaison/scroll-fusionchart-example

**Comment by rousan** [comment]
Hi @isthaison,

You should use `scrollColumn2d` chart type instead of `mscombi2d` for `scroll chart`.

**Comment by isthaison** [comment]
I got it! thanks @rousan

**Comment by rousan** [comment]
You are welcome
