### ISSUE TITLE
bar2d type graph not able to scroll and the UI showing like inconsistent in React Native

### ISSUE THREAD

**Issue by AnilkumarDO** [fusioncharts/react-native-fusioncharts#31]
I have implemented fusion chart (bar2d) type in my react native application. Its working fine, If the data is around 10-12 lines (graph lines) showing fine, But, If its 30 lines, Its getting shrink and adjusting the given height only.

Its not even enabling the scrollview (like flatlist), And the UI looks very inconsistent, Even, I tried to add the scrollview to Fusion Chart, But, Its not working. Because, The view is not getting expand, How to enable scroll, or according to data how to increase the view height.

My output is following screenshot, 
![screen shot 2019-02-26 at 11 41 20 am](https://user-images.githubusercontent.com/46213584/53392674-1cba8280-39c0-11e9-946f-f7eb286af09f.png)

Actual, Which I am looking for is following screenshot.
![screen shot 2019-02-26 at 12 05 58 pm](https://user-images.githubusercontent.com/46213584/53392690-2e038f00-39c0-11e9-950c-da4845117a51.png)

Here I have defined my issue, Please check and give your suggestions to fix the issue.

https://stackoverflow.com/questions/54879739/fusion-chart-bar2d-is-not-able-to-scroll-in-react-native

**Comment by rohanoid5** [comment]
@AnilkumarDO Can you please share the Chart Configuration and the DataSource you are using?

**Comment by AnilkumarDO** [comment]
myArray.map((item, index) => {
    jsonTextValues.push({
      label: item.TextTitle, value: item.value
    });
    jsonAnnotations.push({
      id: 'dyn-label-bg',
      color: '#000000',
      align: 'left',
      type: 'text',
      text: `${item.TextTitle}`,
      fontSize: 100,
      x: '$canvasStartX+30’,
      y: `$dataset.0.set.${index}.ENDY-20`
    });
  });
}




    if (data != nil) {

      const graphData = {

        chart: {

    subcaptionFontSize: '14',
    numDivLines: ‘1’,
    yAxisMinValue: '0',
    yAxisMaxValue: '100',
    showYAxisValues: '0',
    paletteColors: ‘red’,
    useDataPlotColorForLabels: '1',
    showPercentInTooltip: '0',
    divLineAlpha: '0',

        },

        data: [

         jsonTextValues

        ],

        annotations: {

          showBelow: '0',

          autoScale: '1',

          groups: [{

            id: 'user-images',

            items: [

           jsonAnnotations

            ]

          }]

        }

      };

  }

<View style={styles.container} />
<FusionCharts
  type={type}
  width={width}
  height={height} // given 95%
  dataFormat={dataFormat}
  dataSource={dataSource} //dynamic json data which contains around 30 indexes
  libraryPath={fusionChartPath}
/>

**Comment by rohanoid5** [comment]
Hey @AnilkumarDO I was wondering about this:
```
data: [jsonTextValues]
```

The `data` attribute in `dataSource` must be an array of objects but in your sample code you created an array `jsonTextValues` and passed that inside another array which is not correct. The correct format should be `data: jsonTextValues` this instead. Also I created a simple bar2d chart using random data and the size seems to be consistent. I have 30 plots in the sample. 
<img width="227" alt="screenshot 2019-02-26 at 4 36 00 pm" src="https://user-images.githubusercontent.com/11600285/53408586-da576c80-39e4-11e9-8feb-fe5f26abcece.png">

**Comment by AnilkumarDO** [comment]
But, my issue is not only about text, I am looking for scrollview in bar2d. The above UI looks shrinking, I have around 30-40 data, So, I Have to show those many graph lines in UI. Its looking good if the data is 10-12. 
So, How can I achieve this, Can you help me this way, I got stuck here from morning.

**Comment by Biplovkumar** [comment]
@anil use scrollColumn2d ,it may get helped u.

**Comment by rohanoid5** [comment]
@AnilkumarDO we have introduced Scrollable Bar Chart. Please refer to this [link](https://www.fusioncharts.com/dev/upgrading/whats-new#scroll-bar-2d-chart)
