### ISSUE TITLE
npm run build:assets Throws error in ios installation.

### ISSUE THREAD

**Issue by Biplovkumar** [fusioncharts/react-native-fusioncharts#34]
not able to install this library in ios.

Create isssue  Link :-  [https://support.fusioncharts.com/support/tickets/525626](url)

**Comment by Biplovkumar** [comment]
```
/node_modules/react-native-fusioncharts/bin/fc-assets-builder.js:25
  throw new Error(`FusionCharts module dependency template file: ${fcTemplate} does not exist`);
```

**Comment by rohanoid5** [comment]
Hey, @Biplovkumar it looks like your template file `fusioncharts-tpl.html` is in incorrect location. Can you please tell me where does the `assets` folder live in your project?

**Comment by Biplovkumar** [comment]
![Screenshot 2019-03-20 at 4 36 24 PM](https://user-images.githubusercontent.com/30401136/54679853-5d746a00-4b2e-11e9-9ce1-505bef9caca7.png)

**Comment by Biplovkumar** [comment]
> Hey, @Biplovkumar it looks like your template file `fusioncharts-tpl.html` is in incorrect location. Can you please tell me where does the `assets` folder live in your project?

Thanks for reply,i have added my folders.

**Comment by rohanoid5** [comment]
@Biplovkumar as mentioned in the **README** you need to create the `assets` folder in the root of your project, not in the `src` folder. Your issue will get resolved if you follow the **README** carefully. Let me know if you face any other issue regarding this.

**Comment by Biplovkumar** [comment]
1. build:assets :- 
assets/fusioncharts does not exist

**Comment by rohanoid5** [comment]
@Biplovkumar if check [this](https://github.com/fusioncharts/react-native-fusioncharts#setup-for-ios) section of **README**, you can see it says:

> The --fc-library ./assets/fusioncharts option is only required when you copied FusionCharts library in your assets folder.

So, if you haven't included the **FusionCharts** library from **node_modules** then your `build:assets` script should be like following:
`"build:assets": "fc-build-assets --fc-template ./assets/fusioncharts-tpl.html`

**Comment by Biplovkumar** [comment]
![Screenshot 2019-03-20 at 5 20 08 PM](https://user-images.githubusercontent.com/30401136/54682475-0756f500-4b35-11e9-9afd-3623dce7e60b.png)


Same Error :- 

![Screenshot 2019-03-20 at 5 25 02 PM](https://user-images.githubusercontent.com/30401136/54682514-2190d300-4b35-11e9-848e-d640f379c5dc.png)



`import React, { Component } from "react";
import {
  View,
  StyleSheet,
  StatusBar,
  ImageBackground,
  TouchableOpacity,
  SafeAreaView,
  Dimensions,
  Platform,
} from "react-native";
import appstyle from "../../../styles";
import Colors from "../../../Utils/Colors";
import FusionCharts from 'react-native-fusioncharts';


import {
  Button,
  Input,
  Icon,
  Text,
  CheckBox,
  Header,
  Image
} from "react-native-elements";
const { width, height } = Dimensions.get("window");

export default class PressureTemperatureChart extends Component {
  constructor() {
    super();
    this.state = {
      feedback: "",
      pass: "",
      mobile: "",
      password: "",
      passwordConfirmation: "",
      isConfirmationValid: true,
      type: 'column2d',
      width: '100%',
      height: '100%',
      dataFormat: 'json',
      dataSource: {
        chart: {
          caption: "Harry's SuperMart",
          subCaption: 'Top 5 stores in last month by revenue',
          numberprefix: '$',
          theme: 'fint'
        },
        data: [
          { label: 'Bakersfield Central', value: '880000' },
          { label: 'Garden Groove harbour', value: '730000' },
          { label: 'Los Angeles Topanga', value: '590000' },
          { label: 'Compton-Rancho Dom', value: '520000' },
          { label: 'Daly City Serramonte', value: '330000' }
        ]
      }
    }; 

  this.libraryPath = Platform.select({
    // Specify fusioncharts.html file location
    ios: require('../../../../assets/FusionCharts.html'),
    //android: { uri: 'file:///android_asset/fusioncharts.html' }
  });
}

  componentDidMount() {}
  render() {
    return (
      <SafeAreaView style={styles.container}>


          <Header 
            statusBarProps={{ barStyle: "dark-content" }}
            containerStyle={{
              height: height > 500 ? height/11 : 56,
              paddingBottom: height > 500 ? height/50 : 12, 
              justifyContent: 'center',
              alignItems: 'center',
              backgroundColor: Colors.theme,
              borderBottomColor: "transparent"
            }}
            leftComponent={
              <Icon
              underlayColor='transparent'
              onPress={() => this.props.navigation.goBack()}
              name="arrow-left" type='material-community' 
              color={Colors.White} size={height / 30} />
          }
            rightComponent={
                <Icon
                  underlayColor='transparent'
                  //onPress={() => this.notification()}
                  type="ionicon"
                  name="ios-notifications-outline"
                  color="transparent"
                  size={height / 30}
                />
           
            }
          innerContainerStyles={{ alignItems: "center" }}
          centerComponent={{
            text: "Pressure Temperature Chart",
            style: { color: "#fff", fontWeight: "bold", fontSize: height / 45 }
          }}
        />
        <ImageBackground
          style={appstyle.imageBackground}
          resizeMode="stretch"
          source={require("../../../assets/img/dark_theme_background.jpg")}>
      
       <View style={styles.chartContainer}>
          <FusionCharts
            type={this.state.type}
            width={this.state.width}
            height={this.state.height}
            dataFormat={this.state.dataFormat}
            dataSource={this.state.dataSource}
            libraryPath={this.libraryPath} // set the libraryPath property
          />
        </View>


          </ImageBackground>
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.status
  },
  chartContainer: {
    height: 200
  }
});`



Now i will update u after holi ,22-2-19.
not able to add this library.

**Comment by Biplovkumar** [comment]
I have un-installed and install again via these steps :- 

Step 1. :-  npm install react-native-fusioncharts --save

Step 2.  npm install fusioncharts --save

Step 3. Add a build"assets script in Application's package.json file

"scripts": {
    ......
"build:assets": "fc-build-assets --fc-template ./assets/fusioncharts-tpl.html",
},

File structure :- 

![Screenshot 2019-03-22 at 12 28 02 PM](https://user-images.githubusercontent.com/30401136/54805796-07263900-4c9e-11e9-93f9-66bdd790c541.png)


Step 4.  "build:assets": "fc-build-assets --fc-template ./assets/fusioncharts-tpl.html",

and it is worked  but very simple.

![Screenshot 2019-03-22 at 12 32 23 PM](https://user-images.githubusercontent.com/30401136/54805944-96335100-4c9e-11e9-90e9-213a1aa9694e.png)

 
I want like this ,

![pt_chart](https://user-images.githubusercontent.com/30401136/54805857-42286c80-4c9e-11e9-9e0c-c0c91aca4b21.jpeg)

my team mates has used this library and made this via Android Studio (Java).
but i want to implement in react native.

Here is list of chart [https://www.fusioncharts.com/dev/chart-attributes/area2d](url)
but i did not getted like this,
How can i achieve this ?
Please help .
This is the awesome library.

**Comment by rohanoid5** [comment]
@Biplovkumar I did not understand exactly what you are trying to say but based on the last screenshot you provided I'm getting you want to implement a Gauge Chart in your app. Please have a look at [this](https://www.fusioncharts.com/charts/gauges) link.

**Comment by Biplovkumar** [comment]
> @Biplovkumar I did not understand exactly what you are trying to say but based on the last screenshot you provided I'm getting you want to implement a Gauge Chart in your app. Please have a look at [this](https://www.fusioncharts.com/charts/gauges) link.

i want to implement a Gauge Chart in my app like this ?
Which chart shall we use, i am little bit confused ?

![pt_chart](https://user-images.githubusercontent.com/30401136/54806861-5752ca80-4ca1-11e9-8c65-2d6276d85a6a.jpeg)

**Comment by Biplovkumar** [comment]
only showing loading chart ,Please wait ?
What is my mistake ?

I followed this Link Given by library.
![Screenshot 2019-03-22 at 1 34 43 PM](https://user-images.githubusercontent.com/30401136/54809936-bc5eee00-4caa-11e9-8da1-eba42de79213.png)

**Comment by Biplovkumar** [comment]
Any reply ?

**Comment by Biplovkumar** [comment]
Closing ,cause of throwing error resolved by @rohanoid5 .
