### ISSUE TITLE
Not able to show simple gauge (type: 'angulargauge',)

### ISSUE THREAD

**Issue by Biplovkumar** [fusioncharts/react-native-fusioncharts#35]
![Screenshot 2019-03-22 at 4 03 21 PM](https://user-images.githubusercontent.com/30401136/54817154-39469380-4cbc-11e9-9ae6-02c3d0c65dc3.png)

Showing this in webView ?
i am stuck at this point.
Followed Link :- 

[https://www.fusioncharts.com/dev/getting-started/react-native/your-first-gauge-using-react-native](url)

**Comment by Biplovkumar** [comment]
![Screenshot 2019-03-22 at 4 18 29 PM](https://user-images.githubusercontent.com/30401136/54817997-3ea4dd80-4cbe-11e9-9a00-59cb7a1f0a31.png)


Is this only for paid users ?

**Comment by Biplovkumar** [comment]
plz reply ,its urgent ?

**Comment by Biplovkumar** [comment]
Reply ?

**Comment by Biplovkumar** [comment]
i spoiled whole day in angulargaude type but not implemented.

Pie2d, column2d easily implemente.

Please reply ?
ur reply save my job ?
because i am stuck at this point .

**Comment by Biplovkumar** [comment]
![Screenshot 2019-03-22 at 6 14 46 PM](https://user-images.githubusercontent.com/30401136/54823618-67cd6a00-4cce-11e9-9f52-adc62ea1b4b7.png)


Showing this only.

**Comment by rousan** [comment]
@Biplovkumar, Hey can you show me the `fuioncharts-tpl-ios.html` file ?

**Comment by ashok1994** [comment]
@Biplovkumar  We are working on your issue , will get back to you with a solution ASAP

**Comment by Biplovkumar** [comment]
> @Biplovkumar, Hey can you show me the `fuioncharts-tpl-ios.html` file ?

`<!DOCTYPE html>
<html>
  <head>
    
    <script type="text/javascript" src="fusioncharts/fusioncharts.js"></script>
    <script
      type="text/javascript"
      src="fusioncharts/fusioncharts.charts.js"
    ></script>
    <script
      type="text/javascript"
      src="fusioncharts/fusioncharts.powercharts.js"
    ></script>
    <script
      type="text/javascript"
      src="fusioncharts/fusioncharts.timeseries.js"
    ></script>
    <script
      type="text/javascript"
      src="fusioncharts/fusioncharts.maps.js"
    ></script>
    <script
      type="text/javascript"
      src="fusioncharts/maps/fusioncharts.usa.js"
    ></script>
    <script
      type="text/javascript"
      src="fusioncharts/maps/fusioncharts.world.js"
    ></script>
    <script
      type="text/javascript"
      src="fusioncharts/themes/fusioncharts.theme.fint.js"
    ></script>
    <script
      type="text/javascript"
      src="fusioncharts/themes/fusioncharts.theme.ocean.js"
    ></script>
  </head>

  <body></body>
</html>`

**Comment by rohanoid5** [comment]
@Biplovkumar follow these steps to include Angular Gauge type chart in your application.

- In your `fusioncharts-tpl.html` file which you created in `assets`, add the following script tag:
```
<script
      type="text/javascript"
      src="fusioncharts/fusioncharts.widgets.js"
    ></script>
```
- After that run this command:
 `npm run build:assets`

- After this add the chart configuration for angular gauge in your react native component.

**Comment by rohanoid5** [comment]
@Biplovkumar here is how your chart will look like if you follow the given steps.
![Simulator Screen Shot - iPhone X - 2019-03-22 at 18 48 25](https://user-images.githubusercontent.com/11600285/54825789-5edf9700-4cd4-11e9-93d5-c8c89b30fd3d.png)

**Comment by Biplovkumar** [comment]
omg
Thanku so much
@rohanoid5 .
i think u saved my job.
remain implementation i will do it tomm. 
thanku so much 100 times.

**Comment by Biplovkumar** [comment]
> @Biplovkumar follow these steps to include Angular Gauge type chart in your application.
> 
> * In your `fusioncharts-tpl.html` file which you created in `assets`, add the following script tag:
> 
> ```
> <script
>       type="text/javascript"
>       src="fusioncharts/fusioncharts.widgets.js"
>     ></script>
> ```
> * After that run this command:
>   `npm run build:assets`
> * After this add the chart configuration for angular gauge in your react native component.

sir,
Where is Script list and please mention it in [https://www.fusioncharts.com/dev/getting-started/react-native/your-first-gauge-using-react-native](url)

**Comment by Biplovkumar** [comment]
2 things need to know so I re-open.
1. List of all type chart scripts.
2. Name of the gauge type ?
     there Is possible to put Inside the gauge 
      and out side the gauge value   
      rendering, like above image , which I 
      have putted.

Is this possible via this library or not.
Sorry for opening @rohanoid5.

**Comment by Biplovkumar** [comment]
@rohanoid5 has given solution [here](https://github.com/fusioncharts/react-native-fusioncharts/issues/36#issuecomment-475867415) so i am closing this issue.
thanku so much.

**Comment by mehakayaz121** [comment]
i have same issue not ale to show simple gauge (type:'angularguage' but I am not using in react native I am using this in react js can you pleaseeeeeeeeeeeeee solve my issue
