### ISSUE TITLE
Not able to move,on press niddle  ?

### ISSUE THREAD

**Issue by Biplovkumar** [fusioncharts/react-native-fusioncharts#36]
Please reply ?
OnPress event not working ? 
Thanku

**Comment by Biplovkumar** [comment]
Not able to customized !
1.   On Press move the niddle.
2.   Change niddle color.
3.   Devide More than 5 parts.

Nothing more custizable ?

![Screenshot 2019-03-23 at 1 40 23 PM](https://user-images.githubusercontent.com/30401136/54863645-3f4a7c00-4d71-11e9-8ff6-a6e7147ab417.png)

**Comment by Biplovkumar** [comment]
Please reply if Possible ?

**Comment by rohanoid5** [comment]
@Biplovkumar please follow [this](https://www.fusioncharts.com/dev/chart-guide/gauges-and-widgets/angular-gauge) link and go through it. I am sure you will find what you are looking for.

**Comment by Biplovkumar** [comment]
@rohanoid5  
Really nice documentation.
Some of my issues are solved like Change niddle color,Devide More than 5 parts.

i go through the above [link ](https://www.fusioncharts.com/dev/chart-guide/gauges-and-widgets/angular-gauge)  but i can't able to put two types of value Like below image.

1. "placeValuesInside"
2. "placeValuesoutside" 

**1.** Issue :-  Both show at the same time ?
**2.** Issue :-  it is editable on onPress event and able to get both value at the same time ?

![pt](https://user-images.githubusercontent.com/30401136/54867900-024fab00-4dac-11e9-9958-28a7f59846d8.png)


Let me know it is possible or not in react-native-fusioncharts.

**Comment by Biplovkumar** [comment]
Like chart , showing two types of value in gauge (phusion chart) is possible or not ?
Please reply ?
Because I had read all the documentation of angular gauge but not getted solution,so how it is possible  via phusion charts library.

**Comment by Biplovkumar** [comment]
If possible then please reply ?

**Comment by Biplovkumar** [comment]
Please reply ?

**Comment by rohanoid5** [comment]
@Biplovkumar the feature you're asking for isn't supported by the FusionCharts library. But you can buy a product license from [here](https://www.fusioncharts.com/buy) and you can ask for custom functionality. If you want custom functionality buy the license and get in touch with the support team using this [link](https://www.fusioncharts.com/contact-support)

**Comment by Biplovkumar** [comment]
Okay,
Also I am not able to get edited value in render function .I have done editable but value not getting in render function .
Can u help in this ?

**Comment by rohanoid5** [comment]
@Biplovkumar not sure what you mean by: 
> not able to get edited value in render function

**Comment by Biplovkumar** [comment]
Not able to get value,which is edited by onpress.

**Comment by Biplovkumar** [comment]
Editable gauge value ?

A dial is used to point to the data value. To edit the gauge, the mouse pointer can be used by dragging the dial across the radial scale.

**Comment by Biplovkumar** [comment]
Please Reply ?

**Comment by rohanoid5** [comment]
@Biplovkumar if you want to change the position of the dial then I would recommend you to store the dataSource of your chart in the state of your component and then simply mutate the dial value using setState.

**Comment by Biplovkumar** [comment]
I am able to do it via set state ,but I want to mutate value of dial on mouse pointer and show value in text view.
I am able to change dial value via set state from first day.

**Comment by Biplovkumar** [comment]
@rohanoid5  please reply ?

**Comment by Biplovkumar** [comment]
@rohanoid5 
Here i code.

```
events:
 {  
        rendered: (evtObj, argObj) => {
          console.log("evtObj===", evtObj);
          console.log("evt==values=", evtObj.data.updateObject.values[0]);
       },
}
```


Finally i am closing this issue,i have getted value my self.

Lastly i want to say [paid-system](https://github.com/fusioncharts/react-native-fusioncharts/issues/36#issuecomment-476159475)  is very costly.
