### ISSUE TITLE
Charts does not get loaded in release mode

### ISSUE THREAD

**Issue by maheshp27** [fusioncharts/react-native-fusioncharts#4]
Hi ,
Everything just working fine in develop mode on android platform. when tried creating signed apk/running app in release mode, charts not getting displayed .

Is there any additional configurations needed to solve this. 

Please help. Thank you.

**Comment by maheshp27** [comment]
@rousan Could you please help me here?

**Comment by rousan** [comment]
@maheshp27 
please follow the steps below for `Android`:

### For Android

* Create `assets` folder in `android/app/src/main` directory if it doesn't exist.
* Copy `FusionCharts` library in the `assets` folder (in most cases copy `node_modules/fusioncharts` folder).
* Create a file named `fusioncharts.html` in this `assets` folder with the required `FusionCharts` module files. Find the sample html file [here](https://github.com/fusioncharts/react-native-fusioncharts/blob/master/templates/fuioncharts-tpl-android.html).
* Set `libraryPath` property to the `FusionCharts` component as follows:

```html
<FusionCharts
  ......

  libraryPath={{ uri: 'file:///android_asset/fusioncharts.html' }}
 />
```

please let me know if you face any problem.

**Comment by ashok1994** [comment]
Resolved in the latest version , closing for now
