### ISSUE TITLE
How to copy Fusionchart library in assets folder?

### ISSUE THREAD

**Issue by Xumochuan** [fusioncharts/react-native-fusioncharts#55]
Hi, 
Thanks for your publishing amazing react native chart library.
I am going to use your chart lib on my simple chart page.
I have installed react-native-webview and react-native-fusioncharts.
And where can I get Fusionchart library and which assets folder can I copy?
Hope your kind explanation.
Thanks. 
![image](https://user-images.githubusercontent.com/47884397/62430781-961a8600-b753-11e9-85bd-3631283d6eaf.png)

**Comment by soumyasdutta** [comment]
Hi,

Yes, need to install FusionCharts library via NPM as shown below.

$ npm install fusioncharts --save

Please copy the FusionCharts library files (node_modules/fusioncharts folder) in the assets folder.

For reference, you can visit the following documentation link https://www.fusioncharts.com/dev/getting-started/react-native/your-first-chart-using-react-native

Also please check the sample from the following Dropbox link https://www.fusioncharts.com/dev/getting-started/react-native/your-first-chart-using-react-native
