### ISSUE TITLE
Tried to register two views with the same name RNCWebview

### ISSUE THREAD

**Issue by sundeep51652** [fusioncharts/react-native-fusioncharts#58]
Hi, 
I am getting this error 'Tried to register two views with the same name RNGestureHandlerButton'
First I have installed 'react-native-webview' and liked successfully after linking installed 'react-native-fusioncharts' now when I run the app I am getting this error.

React and React Native version I am using
    "react": "16.6.1",
    "react-native": "0.60.5",

**Comment by ayanbhaduryfc** [comment]
You can try out the solutions suggested in this thread - https://github.com/kmagiera/react-native-gesture-handler/issues/451

Still, if you are facing the problem, please share a sample replicating it so that it could be investigated.

**Comment by rohanoid5** [comment]
Fixed in version [`4.1.1`](https://github.com/fusioncharts/react-native-fusioncharts/releases/tag/4.1.1)

**Comment by rohanoid5** [comment]
@sundeep51652 update the module to the latest version and let us know if you find any difficulties.

**Comment by rohanoid5** [comment]
Issue fixed hence closing.
