### ISSUE TITLE
Plan to upgrade to the latest WebView version?

### ISSUE THREAD

**Issue by safaiyeh** [fusioncharts/react-native-fusioncharts#60]
We are using FusionCharts for our charting library; however, we also have a need for WebView in another part of our app.

The WebView version in react-native-fusioncharts does not support v7+. Any plans for migrations? If not, how can I assist migrating? I would spend time to help migrate it this month.

Thanks!
Jason Safaiyeh
jsafaiyeh@sumologic.com

**Comment by safaiyeh** [comment]
cc: @rohanoid5 @yakuzaaaa

**Comment by safaiyeh** [comment]
https://github.com/fusioncharts/react-native-fusioncharts/pull/61

**Comment by rohanoid5** [comment]
@safaiyeh WebView has been moved to devDependecy which solves the issue. Hence closing. Thanks for bringing this to attention.
