### ISSUE TITLE
IOS: Invariant Violation: requireNativeComponent: "RNCWKWebView" was not found in the UIManager. 

### ISSUE THREAD

**Issue by panvourtsis** [fusioncharts/react-native-fusioncharts#62]
After install the library `react-native-fusioncharts` and followed all the required steps i got this error. 

Even after installing react native webview i got this. I tried react-native-webview but doesn;t have any issue without fusioncharts.

![image](https://user-images.githubusercontent.com/6433679/66665941-3f03c680-ec58-11e9-9401-0dcfd69d03b5.png)

these are the packages i am using

"fusioncharts": "^3.14.1"
"react": "^16.10.2"
"react-native": "^0.61.2"
"react-native-fusioncharts": "^4.1.0"
"react-native-webview": "^7.4.1"

**Comment by safaiyeh** [comment]
this library uses react-native-webview@^5.12.1 so you have to use that version of WebViews for it to work

**Comment by rohanoid5** [comment]
@panvourtsis what version of react-native-fusioncharts are you using? Did you try using the latest version 4.1.1
@safaiyeh this library has react-native-webview as a devDependecy, it doesn't depend on any specific version.

**Comment by panvourtsis** [comment]
fyi the @safaiyeh solution worked. @rohanoid5 versions are listed above but all versions are installed as latest

**Comment by safaiyeh** [comment]
@rohanoid5 I understand it is a devDependency, but on a fresh project the library does not work on the latest WebView version because of the UIWebView to WKWebView migration for iOS.

**Comment by rohanoid5** [comment]
@panvourtsis if you update the module now using `npm i react-native-fusioncharts@latest` it will solve the issue. 
@safaiyeh seems like I forgot to publish the latest version 4.1.1 to npm 🤦‍♂  that's why fresh projects were also getting the error because it was installing the version 4.1.0 which had `react-native-webview` as dependency instead of being a devDependency.  Thanks for your input😄 .

**Comment by Subway19** [comment]
@rohanoid5  this is still an issue. We are running into this issue with latest fusioncharts i.e. 4.1.1
