### ISSUE TITLE
Black background flash initially when loading charts (IOS13 Devices only).

### ISSUE THREAD

**Issue by jigartankhupp** [fusioncharts/react-native-fusioncharts#63]
**Description:**

In iOS13 devices when loading chart initially from calling API then setting in state.

Version i am using:
```
"react-native-fusioncharts": "^4.0.0",
"react-native-webview": "^5.12.1",
"fusioncharts": "^3.14.1",
```

![Issue screenshot:](https://i.ibb.co/Pzw5cjR/Screenshot-2019-11-29-at-16-58-30.png) 
External link for screenshot: https://prnt.sc/q3stpg

**Comment by navdeepothee** [comment]
Thanks for getting in touch.

We were able to run the app on both simulators and physical device. As the mentioned issue was reported on physical device we tested the sample on iPhone 7 Plus iOS version 13.1.3.
But we weren't able to replicate the issue. The black flash was not detected. 
​
We have also recorded the same. Please check this attached video for the same.
https://www.dropbox.com/s/9g7wzwo0cpcmn61/RPReplay_Final1576489325.mov?dl=0

![IMG_8810](https://user-images.githubusercontent.com/44605546/71807486-6fa99f80-3091-11ea-9ca2-4f6884d4e2ae.PNG)

**Comment by jigartankhupp** [comment]
Thanks, I am closing this issue as I am able to do fix with patch.

**Comment by adelaadeoye** [comment]
@navdeepothee please could you be of assistance to me, I am working on a project that make uses of Line chart and Fusion msline fit perfectly for the purpose of the app as it accepts null value and it connects only axis that has value. The issue I am having is that the Chart works fine on  an emulator but displays blank on a physical iPhone device. We need to go beta testing next week. 

I am using react-native-fusioncharts 5.1.0 and     "react-native-webview": "^11.6.4", I followed this instruction here https://www.npmjs.com/package/react-native-fusioncharts

Thanks in anticipation
