### ISSUE TITLE
TypeScript definition files missing for react-native-fusioncharts module

### ISSUE THREAD

**Issue by ayanbhaduryfc** [fusioncharts/react-native-fusioncharts#64]
the type definition file is not included for the react-native-fusioncharts module, as a result, VS code is throwing a warning while importing the module.

**Comment by safaiyeh** [comment]
+1 When can we get TypeScript support?

**Comment by rohanoid5** [comment]
Support has been added in the latest version. Please check the version [here](https://github.com/fusioncharts/react-native-fusioncharts/releases/tag/4.1.2).
