### ISSUE TITLE
feedData API method is not working in ReactNative implementation of RealTime data update of FusionTime

### ISSUE THREAD

**Issue by soumyasdutta** [fusioncharts/react-native-fusioncharts#67]
` "rendered": (e) => {
          // let realtimeChart = _ref.sender;

          lastTimeStr = getNextRandomDate(lastTimeStr);
          console.log("new lastTimeStr:", lastTimeStr);

          let newDate = new Date(lastTimeStr);
          console.log("newDate without format:", newDate);

          let formattedNewDate = fd(newDate);
          console.log("new Date first time:", formattedNewDate);

          let incrementor = setInterval(() => {
            console.log("formattedNewDate before randomizing:", formattedNewDate);
            newDate = getNextRandomDate(formattedNewDate);
            formattedNewDate = fd(newDate);

            let final_data = [[formattedNewDate, randBetween(13, 45), 'Kuala Lumpur'],
            [formattedNewDate, randBetween(13, 45), 'Panama City']];

            console.log(final_data);

            // console.log(this.apiCaller(`window.chartObj.setChartAttribute("exportEnabled","1")`));
            // console.log(this.apiCaller(`window.chartObj.setChartAttribute("exportEnabled","1")`));

            this.apiCaller(`window.chartObj.feedData(${final_data})`)

          }, 1000);
        }`
The entire sample could be checked from https://www.dropbox.com/s/ci7z5a9hkbll4su/TimeSeriesRealTimeSample.zip?dl=0

**Comment by rohanoid5** [comment]
feedData API is working. [Here](https://github.com/rohanoid5/timeseries-realtime-react-native) is the implementation. Check it out.

For reference:
```
constructor(props: Props) {
    super(props);

    this.state = {
      type: 'timeseries',
      width: '100%',
      height: '80%',
      dataFormat: 'json',
      dataSource: {
        data: null,
        yAxis: { plottype: 'area' },
        series: 'City'
      },
      schemaJson: schema,
      dataJson: data,
    };

    this.libraryPath = Platform.select({
      // Specify fusioncharts.html file location
      ios: require('./assets/fusioncharts.html'),
      android: {uri: 'file:///android_asset/fusioncharts.html'},
    });

    this.apiCaller = null;
    this.dataUpdater = null;

    this.bindApiCaller = this.bindApiCaller.bind(this);
    this.changeType = this.changeType.bind(this);
  }

changeType() {
    lastTimeStr = getNextRandomDate(lastTimeStr);
    let newDate = new Date(lastTimeStr);
    let formattedNewDate = fd(newDate);

    this.dataUpdater =  setInterval(() => {
      newDate = getNextRandomDate(formattedNewDate);
      formattedNewDate = fd(newDate);
      this.apiCaller(`window.chartObj.feedData([
        ['${formattedNewDate}', ${randBetween(13, 45)}, 'Kuala Lumpur'],
        ['${formattedNewDate}', ${randBetween(13, 45)}, 'Panama City']
      ]);`);
    }, 1000);
  }

  // Bind the argument from onInitialized with the property you created in your constructor
  bindApiCaller(caller: any) {
    // Now this.apiCaller will be a function where you can pass js code for the WebView
    // to access the chart Object. See the method changeType.
    this.apiCaller = caller;
    this.changeType();
  }

  componentWillUnmount() {
    clearInterval(this.dataUpdater);
  }

render() {
    return (
      <View style={styles.container}>
        <FusionCharts
          dataJson={this.state.dataJson}
          schemaJson={this.state.schemaJson}
          type={this.state.type}
          width={this.state.width}
          height={this.state.height}
          dataFormat={this.state.dataFormat}
          dataSource={this.state.dataSource}
          libraryPath={this.libraryPath} // set the libraryPath property
          onInitialized={(caller: any) => {
            this.bindApiCaller(caller);
          }}
        />
      </View>
    );
  }
```

Closing for now.
